# 第11天 异常

## 主要内容

## 1、掌握异常的概念及分类

## 2、掌握异常的处理-捕获异常try、catch和finally

## 3、掌握异常的处理-使用throws声明异常

## 4、掌握使用throw手动抛出异常

## 5、掌握throws和throw的区别

## 6、掌握自定义异常

## 7、熟悉异常的捕获顺序

## 8、掌握方法覆盖与异常

## 9、熟悉异常链机制

## 学习目标

| 节数   | 知识点                                     | 要求 |
|--------|--------------------------------------------|------|
| 第一节 | 掌握异常的概念及分类                       | 掌握 |
| 第二节 | 掌握异常的处理-捕获异常try、catch和finally | 掌握 |
| 第三节 | 掌握异常的处理-使用throws声明异常          | 掌握 |
| 第四节 | 掌握使用throw手动抛出异常                  | 掌握 |
| 第五节 | 掌握throws和throw的区别                    | 掌握 |
| 第六节 | 掌握自定义异常                             | 掌握 |
| 第七节 | 熟悉异常的捕获顺序                         | 掌握 |
| 第八节 | 掌握方法覆盖与异常                         | 掌握 |
| 第九节 | 熟悉异常链机制                             | 掌握 |

## 掌握异常的概念及分类

1.1 异常处理概述

![](media/ae096666c33923333847c055a72459a9.png)

异常：

![](media/72c697352d4338ef3b8aaa5e5c5a151f.png)

错误：

![](media/f677328a44908dedd9a11c6cb8a04b3e.png)

1.2异常层次关系

![](media/2d97da006c1f7b265f369cd89d880f8a.png)

![](media/fa2c1d0fc58d0ecacc29ffa090b49927.png)

![](media/6705f507d38687b526d509e47c39f088.png)

1.3 异常种类

![](media/e2e1009dfc4f479bb3d7fb7ec88b69c2.png)

运行时异常：

![](media/d89bef6b22d7d7dd3356191089696313.png)

![](media/30fa1c8bd4d0bdd5cbd522be8dcd1437.png)

![](media/55f82b9c6a68cd9e7c1a4299e211cd0a.png)

![](media/ced77e28684487226b7a20285726b1ae.png)

![](media/525f86b4de5d1e34ae104cf30cc8d493.png)

![](media/aa2ababaf8583876d56e61a72d093025.png)

编译异常：

![](media/41bf9aa03046284e6a9bed911606219c.png)

### 本节作业

1.理解异常处理概述

2.掌握异常种类

3.掌握层次关系

## 掌握异常的处理-捕获异常try、catch和finally

2.1 异常处理概述

![](media/1f3330c9427026954d47441047b23acc.png)

try:

![](media/fb9e99ad5f851e99a82e499a116cb076.png)

try-catch:

![](media/8ab2e03aac2eafbf6bc5f04eebddc5c5.png)

### 本节作业

1.  理解异常处理概述
2.  try-catch-finally语法

## 掌握异常的处理-使用throws声明异常

throw:

![](media/485773e81897c344efd25d6923a56e37.png)

![](media/47d1c4f204ff674eafd06cafd806fca9.png)

![](media/0e8b333280d72828cf4be95c252d6bb7.png)

## 掌握使用throw手动抛出异常

throws:

![](media/52b91d49c568c245e07da4c2a42985e8.png)

## 掌握throws和throw的区别

![](media/24ba0dee9d52f674d38ed0cb9e1d73f6.png)

## 第六节 掌握自定义异常

6.1 自定义异常

![](media/153bfcad3742be5552d84d8b12e2f54b.png)

6.2 自定义异常定义

![](media/92d562b056b9018692917a960d49f516.png)

6.3 自定义异常使用

![](media/5a0b875a8d75bc5200e78ead74b1332d.png)

**本节作业**

1.  自定义异常
2.  自定义异常的使用

## 第七节 熟悉异常的捕获顺序

7.1 异常捕获顺序

在Java中会有多个catch的情况，那多个异常的捕获也是有一定顺序的。

![](media/fde11bf7ac3a92ed91deafd43352ed5b.png)

上述程序不能通过编译，原因如下：

不能编译通过。因为编译的时候会报错:已捕捉到异常 java.io.IOException。 catch(IOException e)这句有错误。

分析：

对于try..catch捕获异常的形式来说，对于异常的捕获，可以有多个catch。对于try里面发生的异常，他会根据发生的异常和catch里面的进行匹配(怎么匹配，按照catch块从上往下匹配)，当它匹配某一个catch块的时候，他就直接进入到这个catch块里面去了，后面在再有catch块的话，它不做任何处理，直接跳过去，全部忽略掉。如果有finally的话进入到finally里面继续执行。换句话说，如果有匹配的catch，它就会忽略掉这个catch后面所有的catch。对我们这个方法来说，抛出的是IOException，当执行etct.doSomething();时，可能会抛出IOException，一但抛出IOException，它首先进入到catch (Exception e) {}里面，先和Exception匹配，由于IOException extends Exception,根据多态的原则，IOException是匹配Exception的，所以程序就会进入到catch (Exception e) {}里面，进入到第一个catch后，后面的catch都不会执行了，所以catch (IOException e) {}永远都执行不到，就给我们报出了前面的错误:已捕捉到异常 java.io.IOException。

总结：

在写异常处理的时候，一定要把异常范围小的放在前面，范围大的放在后面，Exception这个异常的根类一定要放在最后一个catch里面，如果放在前面或者中间，任何异常都会和Exception匹配的，就会报已捕获到...异常的错误。

## 掌握方法覆盖与异常

8.1 方法覆盖要注意：

![](media/0dec5bdd15bcbced9a43c2b5892afb57.png)

![](media/90dfa3e35b77870a62d4176c0dc07fae.png)

## 熟悉异常链机制

![](media/a16f4983e86cbc6ccf4a7fe119826f8f.png)

![](media/8382ef85c9210e282cea177ada633acd.png)

![](media/beb5b0267f84d108e2682a200d31475d.png)

![](media/aaaf93c3b81edf4feccb8f18eb482b71.png)

![](media/57567721a3c3ff7cdda412166b643283.png)

![](media/bc77a51fdd2c7ff77371f267a1896c02.png)

![](media/dbc652a5541a4de184467b46c4d394b0.png)
